version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: jwt-container
    environment:
      POSTGRES_DB: jwtDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/dataSTGRES_PASSWORD=pass